### ISSUE TITLE
Error: Couldn't install fruitstudios/linkit: Unable to determine the base path

### ISSUE THREAD

**Issue by auralon** [fruitstudios/craft-linkit#15] opened 2018-03-29 08:48 UTC
So, I can't seem to install this plugin.  I've tried several times.  I've also tested other plugins to see if they trigger this error (they don't).

Error: Couldn't install fruitstudios/linkit: Unable to determine the base path

Output: Loading composer repositories with package information
Updating dependencies
Package operations: 1 install, 0 updates, 0 removals
- Installing fruitstudios/linkit (1.0.3): Loading from cache
- Removing fruitstudios/linkit (1.0.3)

**Comment by samhibberd** [comment] 2018-03-29 09:45
Hey @auralon, sorry you are running into issues, we will look into it!

**Comment by brandonkelly** [comment] 2018-03-29 12:39
Hey @auralon are you able to install any other plugins? At first glance I’m not seeing anything wrong with LinkIt that could cause this, so suspect it might be an issue with our [plugin installer Composer plugin](https://github.com/craftcms/plugin-installer).

**Comment by auralon** [comment] 2018-03-29 13:19
@brandonkelly yeah, I cleaned up, then installed another plugin to check and it installed fine.  I've since installed another plugin too, with no issues.  I tried installing linkit 4 times today, all told, to no avail.

**Comment by shornuk** [comment] 2018-03-29 14:30
@auralon - How are you installing? Manually or via the Plugin store?

**Comment by sevfurneaux** [comment] 2018-03-29 22:02
I'm also getting the same error when manually running "composer install" when deploying on [Nanobox](http://nanobox.io/).

See screengrab below:

<img width="793" alt="screen shot 2018-03-29 at 23 59 51" src="https://user-images.githubusercontent.com/1056416/38115780-970d35ec-33ad-11e8-8f8c-4f510e102b3d.png">

Seems to work fine when installing locally.

**Comment by shornuk** [comment] 2018-03-30 07:41
Appears packagist was complaining about the license and was causing it to fail to update.
Try again now and should be ok.

**Comment by johnniefp** [comment] 2018-03-30 14:23
Still failing here. Did a composer clearcache first. (On local it's still updating fine)

`Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing fruitstudios/linkit (1.0.3)
    Downloading: 100%

  - Removing fruitstudios/linkit (1.0.3)

  [craft\composer\InvalidPluginException]
  Couldn't install fruitstudios/linkit: Unable to determine the base path `

**Comment by hybridinteractive** [comment] 2018-03-30 16:15
Same issue here.

**Comment by angrybrad** [comment] 2018-03-30 16:33
Any chance someone is experiencing this issue on a public box and wouldn't mind sharing some CP/SSH credentials with support@craftcms.com?  Want to make sure it's not a bug in our plugin installer.

**Comment by sevfurneaux** [comment] 2018-03-30 19:06
@angrybrad I can't provide a public box, but if its not too much work you could signup for [Nanobox](http://nanobox.io) where I tried? Alternatively @hybridinteractive, @johnniefp and @auralon, do you have a public box for testing?

**Comment by brandonkelly** [comment] 2018-03-30 19:15
Think I just figured it out. Your primary plugin class is `fruitstudios\linkit\Linkit`, with a lowercase `i`, but it lives within [LinkIt.php](https://github.com/fruitstudios/craft-linkit/blob/master/src/LinkIt.php), with a capital `I`. So case-sensitive file systems won't be able to find it when looking for `Linkit.php`.

**Comment by shornuk** [comment] 2018-03-30 20:45
Awesome, thanks guys. This plugin has so far been named `Link It` , `Link it` , `LinkIt` , `Linkit` and so on, so I'm not surprised we got caught out :) Hopefully this will fix it.

**Comment by mikestecker** [comment] 2018-03-30 23:33
Just realized I'm having the same issue. Locally I'm on 1.0.4, install works fine locally but when deploying to my server I get the same error.

**Comment by sevfurneaux** [comment] 2018-03-31 07:53
Interesting you’re still getting the issue @mikestecker following the naming update 🤔 I haven’t tested again myself.

@shornuk maybe there’s more to it than the naming change?

**Comment by shornuk** [comment] 2018-03-31 08:57
@sevfurneaux - possibly. Haven't had time to fully test/replicate yet. @mikestecker - was it the exact same error? Did you run the `composer clearcache` command before trying again?

**Comment by johnniefp** [comment] 2018-03-31 10:20
Wish I had better news but still failing here.

Uninstalled from my mac then composer clearcache
Reinstall Linkit
All fine.

Run clearcache on staging
Deploy to Linux box then run `composer install`

Fails with:
`Installing dependencies (including require-dev) from lock file
  - Installing fruitstudios/linkit (v1.0.4)
    Downloading: 100%

  - Removing fruitstudios/linkit (v1.0.4)

  [craft\composer\InvalidPluginException]
  Couldn't install fruitstudios/linkit: Unable to determine the base path`

**Comment by mikestecker** [comment] 2018-03-31 16:50
@sevfurneaux @shornuk yeah it's the exact same error. I'm seeing the exact same output as @johnniefp: works fine locally on my Mac but when I deploy to my server (I'm using Buddy to deploy) it fails. When I view the logs is when I see the `Unable to determine the base path` error. I then tried to SSH into the server, navigated to the folder, ran `composer clearcache` and then `composer install` but still seeing the same error.

**Comment by angrybrad** [comment] 2018-03-31 19:04
@shornuk looks like your rename didn't make it into the commit. https://github.com/fruitstudios/craft-linkit/commit/8784a389e1db1698cc19ac0c1a42a09ab50db19f

Git is touchy with casing.  Usually you have to do it over multiple commits.  First rename `LinkIt` to `Linkit-temp`, commit, then rename `Linkit-temp` to `Linkit` and commit again.

**Comment by shornuk** [comment] 2018-03-31 19:37
@angrybrad - Thanks Brad. Had missed that. Just pushed new release which should hopefully have it sorted! 🙏

**Comment by johnniefp** [comment] 2018-04-01 10:13
I can confirm all is working fine now, for me at least. Successfully ran `composer install` post deployment on my Linux box without issue.

**Comment by shornuk** [comment] 2018-04-01 21:28
Nice @johnniefp ! Hopefully we’ll get some further confirmations and close this one down. Thanks for testing.

**Comment by mikestecker** [comment] 2018-04-02 15:25
@shornuk sorry to be late to the reply party but the latest change you did worked for me. I'd say feel free to close...

**Comment by shornuk** [comment] 2018-04-02 16:39
@mikestecker no problem! Closing this now then. Thanks for the input everyone.

**Closed by shornuk** 2018-04-02 16:39 UTC

**Comment by auralon** [comment] 2018-04-03 09:12
Sorry for not responding over the past few days, but happy to confirm that it's installing fine here too.  Thank you! :+1:

**Comment by sevfurneaux** [comment] 2018-04-03 09:29
Same here – all good on my end 👍
